checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_code_sniffer:
        config:
            standard: "PSR12"
        filter:
            paths: ['src']
    sensiolabs_security_checker: true
    php_sim: true
    php_cs_fixer:
        config:
            level: psr12
    php_mess_detector: true
    php_analyzer: true
